language: android
android:
  components:
    - platform-tools
    - tools
    - build-tools-24.0.3
    - android-23
    - extra-google-m2repository
    - extra-android-m2repository

before_install:
    - jdk_switcher use oraclejdk8
    - java -version

script:
  ./gradlew build
