language: android
jdk: oraclejdk8
sudo: false
android:
	components:
                - platform-tools
                - build-tools-25.0.0
                - android-25
                - extra-android-m2repository
script:
        - ./gradlew assembleDebug
before_install:
        - chmod +x gradlew
