language: android
android:
	components:
                - platform-tools
                - build-tools-23.0.1
                - android-23
                - extra-android-m2repository
script:
        - ./gradlew assembleDebug
before_install:
        - chmod +x gradlew
